Feature/form pages creation
ErickGrCosta/quasar-blog pull request #5
Opened 2024-04-17 19:48 UTC by ErickGrCosta

Criação das páginas de criação de Posts e de autor, seguindo os padrões pedidos (options API para o authors).

2024-04-17 20:50 UTC, felipejuzo02 requested changes

2024-04-17 20:50 UTC, felipejuzo02 commented on src/components/AppPostCard.vue
> +})
temos costume de definir as props como obj:
```js
const props = defineProps({
  title: {
    type: String,
    default: ...
  },

  ...
  
})
```

2024-04-17 20:50 UTC, felipejuzo02 commented on src/components/AppPostCard.vue
> +          <div class="text-h4 app-post-card__contents full-width ellipsis col-3 bg-light-gray rounded-borders content-center">
Duas coisas:
- Tag poderia ser h4 ja que vc usa text-h4
- Tem necessidade usar `app-post-card-contents`?? o filho ja não herda?

2024-04-17 20:50 UTC, felipejuzo02 commented on src/components/AppPostCard.vue
> +    z-index: 1;
z-index: 1 já é o default nao??

2024-04-17 20:50 UTC, felipejuzo02 commented on src/components/AppPostCard.vue
> +  }
pq nao usar o `border-radius` do quasar?? precisa ser tao especifico assim?

2024-04-17 20:50 UTC, felipejuzo02 commented on src/components/AppPostCard.vue
> +}
Conforme conversado, não é o ideal ter classes utilitarias aq.

Se vc sobreposse o `light-gray` do quasar no .scss, teria realmente necessidade de vc replicar a classe?

2024-04-17 20:50 UTC, felipejuzo02 commented on src/layouts/MainLayout.vue
> +        <q-route-tab to="/authors" label="Autores" />
Loopar

2024-04-17 20:50 UTC, felipejuzo02 commented on src/layouts/MainLayout.vue
> +}
mesmo comentario anterior sobre classes utiltarias

2024-04-17 20:50 UTC, felipejuzo02 commented on src/pages/AuthorsForm.vue
> +        <div class="q-pa-md" style="max-width: 25rem">
Evite usar `style` na view, poderia criar uma classe e aplicar o css

2024-04-17 20:50 UTC, felipejuzo02 commented on src/pages/AuthorsForm.vue
> +            />
`q-input` tem o mesmo padrao em todas as telas, não?? apenas diferenciando as props. Poderia criar um componente pra isso, assim vc não corre o risco de deixar algum diferente dos demais

2024-04-17 20:50 UTC, felipejuzo02 commented on src/pages/AuthorsForm.vue
> +              <q-btn label="Reset" type="reset" color="primary" flat class="q-ml-sm" />
Seu projeto ta em Português, então usar as labels em Português

2024-04-17 20:50 UTC, felipejuzo02 commented on src/pages/AuthorsForm.vue
> +    }
pq o prefixo on? o método ja tem a responsabilidade de resetar, poderia ser apenas `reset` ou `resetValues`

2024-04-17 20:50 UTC, felipejuzo02 commented on src/pages/AuthorsForm.vue
> +      }
Apenas uma melhoria, poderia usar notify do quasar ao inves de console para dar feedback ao usuário, tanto no erro, quanto no sucesso

Outra coisa, se é options, usar o mapActions pra chamar sua ação

2024-04-17 20:50 UTC, felipejuzo02 commented on src/pages/AuthorsList.vue
> +      </div>
e essa div vazia??

2024-04-17 20:50 UTC, felipejuzo02 commented on src/pages/AuthorsList.vue
> +      </div>
pq o `row justify-between` se tem apenas um elemento filho?

2024-04-17 20:50 UTC, felipejuzo02 commented on src/pages/PostForm.vue
> +      </div>
mesmo comentario do de cima

2024-04-17 20:50 UTC, felipejuzo02 commented on src/pages/PostForm.vue
> +        <div class="q-pa-md" style="max-width: 25rem">
style na view

2024-04-17 20:50 UTC, felipejuzo02 commented on src/pages/PostForm.vue
> +            <q-input
Se componentizar o q-input, usar ele

2024-04-17 20:50 UTC, felipejuzo02 commented on src/pages/PostForm.vue
> +            /> -->
apagar comentario

2024-04-17 20:50 UTC, felipejuzo02 commented on src/pages/PostForm.vue
> +const state = reactive({
usar ref

2024-04-17 20:50 UTC, felipejuzo02 commented on src/pages/PostForm.vue
> +    }
conforme alinhado, o select aceita um array de objetos

2024-04-17 20:50 UTC, felipejuzo02 commented on src/pages/PostForm.vue
> +function onReset () {
mesmo comentario da tela de autores

2024-04-17 20:50 UTC, felipejuzo02 commented on src/pages/PostsList.vue
> +          <div v-for="post in store.state.posts.posts" :key="post.id" class="col-12 col-md-6 q-pr-sm q-mb-md">
ao inves de usar o store direto, fazer computada

2024-04-17 20:50 UTC, felipejuzo02 commented on src/pages/PostsList.vue
> +              :image="post.image"
uma coisa que temos bastante costume, ao inves de ter várias props assim, poderia ter uma unica do tipo objeto, chamada `content` por exemplo

2024-04-17 20:50 UTC, felipejuzo02 commented on src/pages/PostsList.vue
> +    }
não entendi o intuito dessa parte

2024-04-17 21:00 UTC, DouglasCalora requested changes

2024-04-17 21:00 UTC, DouglasCalora commented on src/components/AppPostCard.vue
> +      />
Usar props na mesma linha como nos demais

2024-04-17 21:00 UTC, DouglasCalora commented on src/components/AppPostCard.vue
> +const href = 'https://picsum.photos/'
usar const abaixo do defineOptions

2024-04-17 21:00 UTC, DouglasCalora commented on src/components/AppPostCard.vue
> +})
Não tipamos dessa form..., ficaria assim:

```js
const props = defineProps({
  title: {
    type: String,
    default: ''
})
```

E assim por diante.

2024-04-17 21:00 UTC, DouglasCalora commented on src/components/AppPostCard.vue
> +  &__break-spaces {
com o padrão BEM não criamos classes filhas com nome de classes utilitarias, mas sem com o conteudo da classe.

2024-04-17 21:00 UTC, DouglasCalora commented on src/components/AppPostCard.vue
> +}
não usar classes assim

2024-04-17 21:00 UTC, DouglasCalora commented on src/layouts/MainLayout.vue
> +        <q-route-tab to="/authors" label="Autores" />
Usar loop com v-for!

2024-04-17 21:00 UTC, DouglasCalora commented on src/layouts/MainLayout.vue
> +}
não usar essas classes utilitarias, usar as do quasar

2024-04-17 21:00 UTC, DouglasCalora commented on src/pages/AuthorsForm.vue
> +      <div class="row justify-between">
não entendi essa classe flex pra 1 item

2024-04-17 21:00 UTC, DouglasCalora commented on src/pages/AuthorsForm.vue
> +      </div>
espaço abaixo

2024-04-17 21:00 UTC, DouglasCalora commented on src/pages/AuthorsForm.vue
> +        <div class="q-pa-md" style="max-width: 25rem">
não usar style inline

2024-04-17 21:00 UTC, DouglasCalora commented on src/pages/AuthorsForm.vue
> +            class="q-col-gutter-md column"
não precisa da classe row?

2024-04-17 21:00 UTC, DouglasCalora commented on src/pages/AuthorsForm.vue
> +            />
Algumas props estão sendo repetidas entre os inputs, cria uma conts com o que é default:

```js
const inputProps = {
  filled: true,
  lazyRules: true,
  rules: [val => val && val.length > 0 || 'Por favor, digite algo']
}
```

E repasse com v-bind

```html
<q-input v-model="name" label="Nome" v-bind="inputProps" />
```

Obs: este hint "Nome do autor" esta redundante

Usar propriedades na mesma linha como os demais

2024-04-17 21:00 UTC, DouglasCalora commented on src/pages/AuthorsForm.vue
> +            />
mesmas considerações do input acima

2024-04-17 21:00 UTC, DouglasCalora commented on src/pages/AuthorsForm.vue
> +              <q-btn label="Submit" type="submit" color="primary"/>
espaço antes do `/>`

2024-04-17 21:00 UTC, DouglasCalora commented on src/pages/AuthorsForm.vue
> +  name: 'AuthorsForm',
espaço abaixo

2024-04-17 21:00 UTC, DouglasCalora commented on src/pages/AuthorsForm.vue
> +  setup () {
usar created caso necessario

2024-04-17 21:00 UTC, DouglasCalora commented on src/pages/AuthorsForm.vue
> +    }
quando estamos falando de formulario o correto é essas informações estarem agrupadas em um objeto, algo como:

```js
data () {
  return {
    values: {
      name: '',
      email: ''
    }
}
```

2024-04-17 21:00 UTC, DouglasCalora commented on src/pages/AuthorsForm.vue
> +        await this.store.dispatch('authors/createAuthor', {
utilizar `mapActions`

2024-04-17 21:00 UTC, DouglasCalora commented on src/pages/AuthorsForm.vue
> +    },
espaço abaixo

2024-04-17 21:00 UTC, DouglasCalora commented on src/pages/AuthorsForm.vue
> +      } catch (error) {
caso não use o error pode fazer `catch {}`

2024-04-17 21:00 UTC, DouglasCalora commented on src/pages/AuthorsList.vue
> +      <div class="row justify-between">
não entendi esse flex aqui pro h1

2024-04-17 21:00 UTC, DouglasCalora commented on src/pages/AuthorsList.vue
> +        <div class="text-h1 q-my-lg">Listagem de autores</div>
se é text-h1 deveria ser g1

2024-04-17 21:00 UTC, DouglasCalora commented on src/pages/AuthorsList.vue
> +      </div>
remover

2024-04-17 21:00 UTC, DouglasCalora commented on src/pages/IndexPage.vue
>  const state = reactive({
usar `ref`

2024-04-17 21:00 UTC, DouglasCalora commented on src/pages/PostForm.vue
Nome do arquivo deveria ser `PostsForm`

2024-04-17 21:00 UTC, DouglasCalora commented on src/pages/PostForm.vue
> +      </div>
espaço abaixo

2024-04-17 21:00 UTC, DouglasCalora commented on src/pages/PostForm.vue
> +      <div class="row justify-between">
pq esse flex?

2024-04-17 21:00 UTC, DouglasCalora commented on src/pages/PostForm.vue
> +            />
Mesmas considerações que fiz sobre o outro input de authors

2024-04-17 21:00 UTC, DouglasCalora commented on src/pages/PostForm.vue
> +              <q-btn label="Submit" type="submit" color="primary"/>
espaço antes do `/>`

2024-04-17 21:00 UTC, DouglasCalora commented on src/pages/PostForm.vue
> +    await store.dispatch('authors/fetchAuthors')
espaço abaixo

2024-04-17 21:00 UTC, DouglasCalora commented on src/pages/PostForm.vue
> +    }
Remover conforme falamos

2024-04-17 21:00 UTC, DouglasCalora commented on src/pages/PostForm.vue
> +  }
se não for usar error `catch {}`

2024-04-17 21:00 UTC, DouglasCalora commented on src/pages/PostForm.vue
> +    })
```js
await store.dispatch('posts/createPost', state.value) // considerando que state seja um ref
```

2024-04-17 21:00 UTC, DouglasCalora commented on src/pages/PostForm.vue
> +    onReset()
espaço acima

2024-04-17 21:00 UTC, DouglasCalora commented on src/pages/PostForm.vue
> +    console.error('Erro: ', error)
mesmo comentario sobre o catch n usar o error

2024-04-17 21:00 UTC, DouglasCalora commented on src/pages/PostsList.vue
> +      <div class="row justify-between">
pq esse flex?

2024-04-17 21:00 UTC, DouglasCalora commented on src/pages/PostsList.vue
> +        <div class="text-h1 q-mt-md">
usar h1 se é text-h1

2024-04-17 21:00 UTC, DouglasCalora commented on src/pages/PostsList.vue
> +      </div>
espaço abaixo

2024-04-17 21:00 UTC, DouglasCalora commented on src/pages/PostsList.vue
> +        <div class="row q-mt-sm">
n falta usar o `q-col-gutter-md` para espamento entre os posts?

2024-04-17 21:00 UTC, DouglasCalora commented on src/pages/PostsList.vue
> +          <div v-for="post in store.state.posts.posts" :key="post.id" class="col-12 col-md-6 q-pr-sm q-mb-md">
usar uma computada `posts` pra isto.

2024-04-17 21:00 UTC, DouglasCalora commented on src/pages/PostsList.vue
> +              :image="post.image"
usar `v-bind="post"`

2024-04-17 21:00 UTC, DouglasCalora commented on src/pages/PostsList.vue
> +              :image="post.image"
nem precisaria... só usar v-bind @felipejuzo02

2024-04-17 21:00 UTC, DouglasCalora commented on src/pages/PostsList.vue
> +    }
remover se não tem necessidade.

2024-04-17 21:00 UTC, DouglasCalora commented on src/pages/PostsList.vue
> +  } catch (error) {
mesmo comentario sobre error com catch

2024-04-17 21:11 UTC, eliasassuncao requested changes

2024-04-17 21:11 UTC, eliasassuncao commented on src/components/AppPostCard.vue
> +      <q-badge class="app-post-card__category-tag absolute text-weight-bold text-white bg-red q-mt-md q-py-sm q-px-md">
- poderia ser somente `__category`
- precisa ter o bg-red? acho q era somente para teste né?

2024-04-17 21:11 UTC, eliasassuncao commented on src/components/AppPostCard.vue
> +        <div class="app-post-card__contents full-width column col-9 q-pa-sm">
faz mais sentido `__content`

2024-04-17 21:11 UTC, eliasassuncao commented on src/components/AppPostCard.vue
> +})
definimos a prop declarando default. Por tanto ficaria dessa forma:
```js
const props = defineProps({
  title: {
    type: String,
    default: ''
  },

  smallDescription: {
    type: String,
    default: ''
  },
  ...
})
```

2024-04-17 21:11 UTC, eliasassuncao commented on src/components/AppPostCard.vue
> +    border-radius: 0 2rem 2rem 0;
borda do quasar não resolve?

2024-04-17 21:11 UTC, eliasassuncao commented on src/components/AppPostCard.vue
> +    border-radius: 5px;
borda do quasar não resolve?

2024-04-17 21:11 UTC, eliasassuncao commented on src/components/AppPostCard.vue
> +  color: #ffffff80 !important;
quando queremos sobrepor alguma variavel do quasar, sobrepomos globalmente. Mas pra este caso, não existe nenhuma cor semelhante a essa na palheta do quasar? https://quasar.dev/style/color-palette#color-list

2024-04-17 21:11 UTC, eliasassuncao commented on src/components/AppPostCard.vue
> +  background: #ffffff80 !important;
quando queremos sobrepor alguma variavel do quasar, sobrepomos globalmente. Mas pra este caso, não existe nenhuma cor semelhante a essa na palheta do quasar? https://quasar.dev/style/color-palette#color-list

2024-04-17 21:11 UTC, eliasassuncao commented on src/layouts/MainLayout.vue
> +        <q-route-tab to="/authors" label="Autores" />
utilizar name nos `to`. `to="{ name: 'X' }"`

2024-04-17 21:11 UTC, eliasassuncao commented on src/layouts/MainLayout.vue
> +}
quando queremos sobrepor alguma variavel do quasar, sobrepomos globalmente. Mas pra este caso, não existe nenhuma cor semelhante a essa na palheta do quasar? https://quasar.dev/style/color-palette#color-list

2024-04-17 21:11 UTC, eliasassuncao commented on src/pages/AuthorsForm.vue
> +      </div>
quebrar linha

2024-04-17 21:11 UTC, eliasassuncao commented on src/pages/AuthorsForm.vue
> +        <div class="q-pa-md" style="max-width: 25rem">
não é recomendado utilizar style, só para casos especificos. Pra esse caso uma classe resolveria

2024-04-17 21:11 UTC, eliasassuncao commented on src/pages/AuthorsForm.vue
> +              :rules="[ val => val && val.length > 0 || 'Por favor, digite algo']"
esse tipo de validação, pode ser com que vc reutilize em algum outro lugar. Para isso, é recomendado vc criar uma pasta utils, q é onde armazenamos funções que precisamos reutilizar. Nos projetos vai ser comum vc ver uma pasta chamada `helpers` para isso, mas agr mudamos nosso padrão, para projetos novos chamamos de `utils`.

Então para isso, crie uma pasta `src/utils` onde terá um `index.js` que exporta todas funções, e crie um `required.js` para adicionar essa função `val => val && val.length > 0 || 'Por favor, digite algo'`

2024-04-17 21:11 UTC, eliasassuncao commented on src/pages/AuthorsForm.vue
> +              :rules="[ val => val && val.length > 0 || 'Por favor, digite algo']"
o mesmo comentário em relação ao `utils`

2024-04-17 21:11 UTC, eliasassuncao commented on src/pages/AuthorsForm.vue
> +  },
utilizar mapGetters

2024-04-17 21:11 UTC, eliasassuncao commented on src/pages/AuthorsForm.vue
> +        })
quebrar linha

2024-04-17 21:11 UTC, eliasassuncao commented on src/pages/AuthorsForm.vue
> +    onReset () {
quebrar linha

2024-04-17 21:11 UTC, eliasassuncao commented on src/pages/AuthorsList.vue
> +      </div>
remover div vazia

2024-04-17 21:11 UTC, eliasassuncao commented on src/pages/PostForm.vue
> +      </div>
quebrar linha entre elementos irmãos

2024-04-17 21:11 UTC, eliasassuncao commented on src/pages/PostForm.vue
> +        <div class="q-pa-md" style="max-width: 25rem">
não é recomendado utilizar style, e  sim classe

2024-04-17 21:11 UTC, eliasassuncao commented on src/pages/PostForm.vue
> +                val => val.length < 50 || 'O limite máximo é de 50 caracteres',
utilizar/criar utils conforme outro comentário. O mesmo vale para outros rules da mesma página

2024-04-17 21:11 UTC, eliasassuncao commented on src/pages/PostForm.vue
> +            /> -->
remover campo comentado

2024-04-17 21:11 UTC, eliasassuncao commented on src/pages/PostForm.vue
> +const state = reactive({
- utilizar ref conforme doug comentou
- faz mais sentido chamar de `formValues`

2024-04-17 21:11 UTC, eliasassuncao commented on src/pages/PostForm.vue
> +    }
vc pode criar uma computada para normalizar os dados para usar nas options da forma q vc precisa. Mas acredito que com um só `.map()` é possivel normalizar oq vc precisa.

2024-04-17 21:11 UTC, eliasassuncao commented on src/pages/PostForm.vue
> +    })
- vc poderia mandar diretamente o `formValues`, não precisa copiar e colar o nome das chaves.
- Após criar, você poderia redirecionar para página de listagem, ou criar uma notificação para dar o feedback que deu certo a criação. O mesmo poderia acontecer com o erro, caso der erro avisar o usuário q deu erro

2024-04-17 21:11 UTC, eliasassuncao commented on src/pages/PostsList.vue
> +    const posts = store.state.posts.posts
utilizar computada para isso

2024-04-17 21:11 UTC, eliasassuncao commented on src/pages/PostsList.vue
> +      <div class="q-my-lg">
quebrar linha entre irmãos

2024-04-17 21:11 UTC, eliasassuncao commented on src/router/routes.js
> +      { path: '', name: 'PostsList', component: () => import('pages/PostsList.vue') },
quebrar linha entre as chaves, fica melhor de ver

2024-04-17 22:01 UTC, DouglasCalora commented on src/pages/PostForm.vue
> +    }
@eliasassuncao Não precisa, o componente do quasar tem o `option-label` e `option-value` para isto, não precisa normalizar esses dados...

2024-04-18 03:31 UTC, ErickGrCosta commented on src/components/AppPostCard.vue
> +      <q-badge class="app-post-card__category-tag absolute text-weight-bold text-white bg-red q-mt-md q-py-sm q-px-md">
O bg-red é pra dar uma cor de fundo a tag mesmo.

2024-04-18 03:39 UTC, ErickGrCosta commented on src/components/AppPostCard.vue
> +    z-index: 1;
Infelizmente não

2024-04-18 03:41 UTC, ErickGrCosta commented on src/components/AppPostCard.vue
> +  }
Testei do Quasar e não ficou da forma como gostaria... Gostaria de poder personalizar

2024-04-18 03:41 UTC, ErickGrCosta commented on src/components/AppPostCard.vue
> +    border-radius: 5px;
Testei do Quasar e não ficou da forma como gostaria... Gostaria de poder personalizar

2024-04-18 03:45 UTC, ErickGrCosta commented on src/layouts/MainLayout.vue
> +}
É que estou usando exatamente o código da página do figma que montei, por isso essa especificidade.

2024-04-18 04:02 UTC, ErickGrCosta commented on src/layouts/MainLayout.vue
> +        <q-route-tab to="/authors" label="Autores" />
Dentro do objeto ficou bugado... se colocasse path: {name: '/'}, ele considerava {"name": "/"}, e não funcionava.

2024-04-18 04:06 UTC, ErickGrCosta commented on src/pages/AuthorsForm.vue
> +        <div class="q-pa-md" style="max-width: 25rem">
Veio do próprio quasar! Mas justo.

2024-04-18 13:40 UTC, ErickGrCosta commented on src/pages/AuthorsForm.vue
> +              :rules="[ val => val && val.length > 0 || 'Por favor, digite algo']"
Fiz a sugestão do Doug, mais por achar um pouco mais rápida para esta situação, mas gostei do padrão!

2024-04-18 19:29 UTC, ErickGrCosta commented on src/pages/PostsList.vue
> +      <div class="row justify-between">
Jogar os botões do lado direito da tela.

2024-04-18 20:19 UTC, felipejuzo02 commented on src/pages/AuthorsForm.vue
> +  }
pq nao passa o inputProps direto?

2024-04-18 20:19 UTC, felipejuzo02 commented on src/pages/PostsForm.vue
> +}
poderia ser:
```js
function reset () {
  const valuesToReset = ['title', 'smallDescription', ...]

  valuesToReset.forEach(item => formValues.value[item] = '')
}
```

2024-04-18 20:39 UTC, eliasassuncao requested changes

2024-04-18 20:39 UTC, eliasassuncao commented on quasar.config.js
> +      config: { notify: 'message' },
quebrar linha

2024-04-18 20:39 UTC, eliasassuncao commented on src/components/AppPostCard.vue
> +      />
só quebra qd é na mesma linha

2024-04-18 20:39 UTC, eliasassuncao commented on src/components/AppPostCard.vue
> +          <q-btn rounded color="primary full-width" label="Ler o artigo" to="" />
:to está vazio?

2024-04-18 20:39 UTC, eliasassuncao commented on src/pages/AuthorsForm.vue
> +      <div>
precisa dessa div?

2024-04-18 20:39 UTC, eliasassuncao commented on src/pages/AuthorsForm.vue
> +
não precisa desse espaço já q é o começo do "objeto"

2024-04-18 20:39 UTC, eliasassuncao commented on src/pages/IndexPage.vue
> +    authors.value = store.state.authors
quebrar linha pra ter um espacinho encima

2024-04-18 20:39 UTC, eliasassuncao commented on src/pages/PostsForm.vue
> +      </div>
precisa dessa div?

2024-04-18 20:39 UTC, eliasassuncao commented on src/pages/PostsForm.vue
> +            <q-select v-model="formValues.selectedAuthor" map-options emit-value option-value="id" :options="authors" option-label="name" label="Autores" />
quebrar props igual as de cima

2024-04-18 20:39 UTC, eliasassuncao commented on src/pages/PostsList.vue
> +            />
não precisa quebrar quando é uma unica prop

2024-04-18 20:39 UTC, eliasassuncao commented on src/router/routes.js
> +      { path: '/new', name: 'PostCreate', component: () => import('src/pages/PostsForm.vue') }
quebrar linha eu quis dizer nesse sentido:
```js
{ 
   path: '', 
   name: 'PostsList', 
   component: () => import('pages/PostsList.vue') 
},
{ 
   path: '/authors', 
   name: 'AuthorsList', 
   component: () => import('src/pages/AuthorsList.vue')
},
...
```

2024-04-19 01:49 UTC, ErickGrCosta commented on quasar.config.js
> +      config: { notify: 'message' },
É que nem mexi kk, vinha assim! Mas eu vou quebrar.

2024-04-19 01:52 UTC, ErickGrCosta commented on src/pages/AuthorsForm.vue
> +  }
Passando direto não está funcionando...

2024-04-19 12:35 UTC, felipejuzo02 approved these changes

2024-04-19 12:35 UTC, felipejuzo02 commented on src/components/AppPostCard.vue
> +            <h4 class="ellipsis"> {{ props.title }} </h4>
remover esse espaço entre o titulo, se for pra usar espaço assim, usar margin/padding

2024-04-19 12:35 UTC, felipejuzo02 commented on src/components/AppPostCard.vue
> +            <div class="app-post-card break-spaces q-pl-md col-8">
nao faz sentido vc ter a classe `app-post-card` aqui, remover

2024-04-19 12:35 UTC, felipejuzo02 commented on src/components/AppPostCard.vue
> +}
classe utilitaria dentro do arquivo vue?? ou joga pra um arquivo scss (app no seu caso), ou entao se for usar somente em um lugar, aplicar padrao bem

2024-04-19 12:35 UTC, felipejuzo02 commented on src/pages/AuthorsForm.vue
> +      <div class="q-my-lg">
essa identação me parece errada

2024-04-19 12:35 UTC, felipejuzo02 commented on src/pages/IndexPage.vue
> +    authors.value = store.state.authors
Dúvida... pq vc atribui o state de authors em uma ref ao inves de usar o proprio state aonde precisa?? ou diretamente ou por uma computada

2024-04-19 12:35 UTC, felipejuzo02 commented on src/pages/PostsForm.vue
> +          >
essa > ta no lugar errado, nao??

2024-04-19 12:35 UTC, felipejuzo02 commented on src/pages/PostsForm.vue
> +  valuesToReset.forEach((item) => {
quebrar uma linha apos a const

2024-04-19 13:26 UTC, ErickGrCosta commented on src/pages/IndexPage.vue
> +    authors.value = store.state.authors
Pode ignorar essa página, já já vou excluir ela

2024-04-19 13:30 UTC, DouglasCalora requested changes

2024-04-19 13:30 UTC, DouglasCalora commented on quasar.config.js
> +      config: { notify: 'message' },
O que é e pra que precisa disto?

2024-04-19 13:30 UTC, DouglasCalora commented on src/components/AppPostCard.vue
> +      />
Usar na mesma linha

2024-04-19 13:30 UTC, DouglasCalora commented on src/components/AppPostCard.vue
> +}
não usar classes utilitarias dentro do arquivo vue como ja falamos.

2024-04-19 13:30 UTC, DouglasCalora commented on src/css/app.scss
> +  background-color: #2E5301 !important;
precisa desses !important?

2024-04-19 13:30 UTC, DouglasCalora commented on src/pages/AuthorsForm.vue
> +        <h1 class="q-my-lg">Página de criação de Autor</h1>
indentação errada

2024-04-19 13:30 UTC, DouglasCalora commented on src/pages/AuthorsForm.vue
> +            />
esta errado, usar na mesma linha

2024-04-19 13:30 UTC, DouglasCalora commented on src/pages/AuthorsForm.vue
> +        Notify.create(error)
Não precisa tratar o erro? o que seria o erro?

2024-04-19 13:30 UTC, DouglasCalora commented on src/pages/IndexPage.vue
> +const authors = ref('')
usar o state

2024-04-19 13:30 UTC, DouglasCalora commented on src/pages/PostsForm.vue
> +      <h1 class="q-my-lg">Página de criação de Post</h1>
espaço abaixo

2024-04-19 13:30 UTC, DouglasCalora commented on src/pages/PostsForm.vue
> +defineOptions({ name: 'PostForm' })
PostsForm

2024-04-19 13:30 UTC, DouglasCalora commented on src/pages/PostsForm.vue
> +  }
seria interessante criar uma função "fetchAuthors" e só chamar ela no mounted

2024-04-19 13:30 UTC, DouglasCalora commented on src/pages/PostsForm.vue
> +  valuesToReset.forEach((item) => {
Você já tem o objeto contendo todas informações, poderia fazer:

```js
Object.keys(formValues.value).forEach(key => {
  formValues.value[item] = ''
})
```

2024-04-19 13:30 UTC, DouglasCalora commented on src/pages/PostsList.vue
> +      <div class="row justify-between">
use text-right

2024-04-19 13:30 UTC, DouglasCalora commented on src/pages/PostsList.vue
> +          <h1>Blog</h1>
indentação parece errado e dar espaço abaixo, e não faltou classe pro h1?

2024-04-19 13:30 UTC, DouglasCalora commented on src/pages/PostsList.vue
> +
remover espaço vazio

2024-04-19 13:30 UTC, DouglasCalora commented on src/pages/PostsList.vue
> +          <div v-for="post in posts" :key="post.id" class="col-12 col-md-6 q-pr-sm q-mb-md">
pra que usar padding/magin quando ta usando q-col-gutter?

2024-04-19 13:30 UTC, DouglasCalora commented on src/pages/PostsList.vue
> +  }
criar função fetchPosts

2024-04-19 13:30 UTC, DouglasCalora commented on src/pages/PostsList.vue
> +}
usar classes do quasar ao invés de estilizar tag

2024-04-19 13:30 UTC, DouglasCalora commented on src/utils/required.js
nome do arquivo não esta fazendo sentido para o que de fato tem, talvez mudar para `rules`

2024-04-19 13:30 UTC, DouglasCalora commented on src/utils/required.js
> +export function required (val) {
Não abrir, por exemplo `val`, use `value`

2024-04-19 13:30 UTC, DouglasCalora commented on src/utils/required.js
> +  return (val && val.length > 0) || 'Por favor, digite algo'
- Não precisaria verificar o `lengh > 0` poderia fazer `value && !!value.length`
- "'Por favor, digite algo'" não é usado normalmente, poderia ser `Campo obrigatório.`

2024-04-19 13:30 UTC, DouglasCalora commented on src/utils/required.js
> +export const inputProps = {
`rulesProps`

2024-04-19 13:30 UTC, DouglasCalora commented on src/utils/required.js
> +  filled: true,
esse `filled` não tem a ver com rules mas com style, não deveria estar aqui

2024-04-19 13:30 UTC, DouglasCalora commented on src/pages/AuthorsList.vue
> +        <h1>Listagem de autores</h1>
não faltou estilização do h1?

2024-04-19 13:30 UTC, DouglasCalora commented on src/pages/AuthorsForm.vue
> +        <h1 class="q-my-lg">Página de criação de Autor</h1>
indentação errada, e n faltou estilização?

2024-04-19 13:38 UTC, ErickGrCosta commented on quasar.config.js
> +      config: { notify: 'message' },
Fazer o notify funcionar.

2024-04-19 13:40 UTC, ErickGrCosta commented on src/css/app.scss
> +  background-color: #2E5301 !important;
Precisa pois estou sobrescrevendo as classes do quasar. Se tiver a cor que eu quero não fica.

2024-04-19 13:42 UTC, ErickGrCosta commented on src/pages/AuthorsForm.vue
> +        Notify.create(error)
Chefe, é só para ter alguma coisa, se tivesse mais tempo dava pra pensar em um tratamento.

2024-04-19 13:43 UTC, ErickGrCosta commented on src/pages/AuthorsList.vue
> +        <h1>Listagem de autores</h1>
Aparentemente não...

2024-04-19 14:14 UTC, DouglasCalora approved these changes

2024-04-19 14:29 UTC, eliasassuncao approved these changes

2024-04-19 14:29 UTC, merged